name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkot Source
        uses: actions/checkout@v4
      - name: login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t aws26kathir/reactdevops .
      - name: Publish image to docker hub
        run: docker push aws26kathir/reactdevops:latest
  deploy:
    needs:build
    runs-on: aws-ec2


        
